### ISSUE TITLE
[Feature] Course Card Redesign

### ISSUE THREAD

**Issue by DCRepublic** [swat-sccs/planner#6]
Current iteration of the coursecard is quite cluttered. Fix in [CourseCard.tsx](https://github.com/swat-sccs/scheduler-v2/blob/main/components/CourseCard.tsx) and re order the information so it is more human readable.

**Comment by DCRepublic** [comment]
![course-card](https://github.com/user-attachments/assets/389177f3-1c3a-4d28-ac6a-a0e29faa3c45)
@v6ctor has provided an updated card design.

 Implementation TBD

**Comment by v6ctor** [comment]
![card-3](https://github.com/user-attachments/assets/9900b219-cb9c-4084-acdc-3daa9089007a)
Updated card design to look closer to our end goal with our rating system.
